### ISSUE TITLE
zookeeper集群怎么配置

### ISSUE THREAD

**Issue by koy1619** [dubboclub/dubbokeeper#118]
dubbo.registry.address=zookeeper://127.0.0.1:2181
这一行怎么配置多个zookeeper地址

比如以下配置可以用逗号隔开
peeper.zookeepers=127.0.0.1:2180,127.0.0.1:2181,127.0.0.1:2182

**Comment by sapphire1990** [comment]
dubbo.registry.address=zookeeper://127.0.0.1:2180?backup=127.0.0.1:2181,127.0.0.1:2182

**Comment by koy1619** [comment]
@sapphire1990 亲测可用，非常感谢！！
