### ISSUE TITLE
关于Monitor应用大盘没有数据的可以试试这样

### ISSUE THREAD

**Issue by kanchi240** [dubboclub/dubbokeeper#122]
<dubbo:monitor protocol="registry" />
dubbo.monitor.protocol=registry
两个都配置上试试，我这里配置单独一个不行，两个都配置上就行了

**Comment by zdRan** [comment]
这个配置是要写在哪里？ @kanchi240

**Comment by kanchi240** [comment]
配置在你自己工程的配置文件
