### ISSUE TITLE
使用mysql-storage时，ApplicationMapper.listApps()返回空，请问ApplicationInfo是什么时候插入到mysql的

### ISSUE THREAD

**Issue by tzxyz** [dubboclub/dubbokeeper#138]
启动server，ui，应用大盘数据为空。
logs目录下dubbokeeper/Monitor-writer.log为空
logs目录下没有Application-Writer.log的文件
logs目录下dubbokeeper/DubboKeeper.log `select lower(name) as name,type from application`一直是空

请问ApplicationInfo是什么时候插入到mysql的?

**Comment by ipanocloud** [comment]
遇到类似问题,一直没有解决
