### ISSUE TITLE
缺少javassist.jar包

### ISSUE THREAD

**Issue by 501956430** [dubboclub/dubbokeeper#50]
mysql-dubbokeeper-server  and  mysql-dubbokeeper-ui 项目 似乎缺少javassist.jar包,否则启动编译异常,查找了pom.xml 未发现有引入相关javassist.jar包.

![image](https://cloud.githubusercontent.com/assets/20204491/16481600/a3c33612-3ede-11e6-945f-86dac915bb9c.png)

**Comment by 501956430** [comment]
也许因为我使用的是dubbo.2.5.3.jar

**Comment by bieberHe** [comment]
你看看是不是有两个javassist的包？因为dubbo会应用javassist的，不需要另外引用

**Comment by 501956430** [comment]
@bieberHe dubbo.jar的确是有javassist包的引用，不过编译之后的项目中的确没有javassist包，应该是dubbo  mavne私服空间没有javassist.jar包，导致没有下载下来。
我生产环境的dubbo rpc 也是手动引入javassist.jar。
