### ISSUE TITLE
希望服务的properties可配置服务的timeout时间 

### ISSUE THREAD

**Issue by 501956430** [dubboclub/dubbokeeper#58]
dubbo默认timeout 1000ms ，不知道properties配置里面是否有变量可配置timeout的？ ，不然得自己去jar包里面修改配置文件,如果没有希望能够提供，谢谢。
![qq 20160804183509](https://cloud.githubusercontent.com/assets/20204491/17398993/5a4d388e-5a72-11e6-8f07-07a5e0867ab0.png)

**Comment by 501956430** [comment]
支持一下dubbokeeper.

dubbokeeper一旦数据多了，超时可真是非常的频繁出现，现在才10w 就已经无法拉出时间，默认的1000ms比如是不够

**Comment by bieberHe** [comment]
后端的server建议部署多个节点，如果是一个节点，承受不住太大引用写，主要是写的太平凡，导致数据库锁比较严重

**Comment by dyc87112** [comment]
不好意思，貌似跟我刚才提的#80 是一个问题。

现在在这里改了一下超时时间来解决：

`dubbokeeper-ui/src/main/resources/META-INF/spring/init.xml` 

```xml
    <dubbo:reference interface="com.dubboclub.dk.storage.StatisticsStorage" check="false"
                     id="statisticsStorage" timeout="60000"/>
```
