### ISSUE TITLE
启动monitor时缺少statistics_mysql表

### ISSUE THREAD

**Issue by RainAndDie** [dubboclub/dubbokeeper#59]
完成配置后启动发现未建立statistics_mysql表 能提供一份statistics_mysql表结构吗 谢谢

**Comment by bieberHe** [comment]
在源码的doc目录下面有，可以看看

**Comment by wphmoon** [comment]
里面只有application.sql啊，statistics_XXX表难道是自动生成的

**Comment by bieberHe** [comment]
dui
