### ISSUE TITLE
dubbokeeper-ui 部署在tomcat7，jdk7时，zoopeeper功能报错

### ISSUE THREAD

**Issue by stoneluo** [dubboclub/dubbokeeper#66]
![image](https://cloud.githubusercontent.com/assets/6244732/18509066/66181f88-7aa9-11e6-9ca7-16553ae045c7.png)

**Comment by bieberHe** [comment]
没启动后端的server服务

**Comment by stoneluo** [comment]
@bieberHe 这个功能是查看zk数据，但是运行在jdk7时就报了异常，用jdk8就没有问题

**Comment by stoneluo** [comment]
@bieberHe 感谢！是我搞错了， 配置了的zk服务不正常导致的报错，与jdk没有关系
