### ISSUE TITLE
缺少setting.sh 文件 

### ISSUE THREAD

**Issue by zhangyq1011** [dubboclub/dubbokeeper#67]
![bin](https://cloud.githubusercontent.com/assets/7411134/19995497/bee7ed44-a292-11e6-9440-902c854b97f8.png)
可执行文件夹下缺少setting.sh 文件。

**Comment by qct** [comment]
在Linux下运行  环境变量的设置已经包含在了  `start-*.sh `中，所以不需要`settings.sh`了
