### ISSUE TITLE
dubbokeeper 不支持 dubbox 2.8.4吗?

### ISSUE THREAD

**Issue by yinlsea** [dubboclub/dubbokeeper#73]
我的dubbo环境是当当的dubbox 2.8.4：
打包出来的是dubbo 2.5.3，能运行但是没有任何报错，但是application没有任何数据，怀疑不支持dubbox 2.8.4，所以尝试更换JAR包，换成dubbox 2.8.4.jar以后，dubbokeeper-ui就启动不了了，也没有什么报错。

**Comment by yinlsea** [comment]
解决了，把spring换成3.2.9，不用4.1.6就行了

**Comment by qingnianban** [comment]
哥们为什么，dubbo.registry.address=zookeeper://127.0.0.1:2181可以启动，但是换成公司的fat ip就不行了，2.5.3是可以的

**Comment by qingnianban** [comment]
我已经换成3.2.9了
