### ISSUE TITLE
条件路由配置警告

### ISSUE THREAD

**Issue by tonydzt** [dubboclub/dubbokeeper#98]
条件路由配置失败，如下图，我的消费者和过滤条件都是配置的同一个ip地址，为何会提示“输的地址可以是ip段(192.168.0.*)也可以可是具体ip地址，多个通过逗号分隔开”？哪里有错误呢
![image](https://cloud.githubusercontent.com/assets/20101194/24538434/bc8f3eb0-161b-11e7-8cb4-98df9e2b0a1f.png)

**Comment by qct** [comment]
谢谢  提出来。。。是个bug  已经修复，你可以拉取master
